apiVersion: v1
kind: Secret
metadata:
  name: server-secret
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  JWT_SECRET: {{ .Values.server.jwt.secret | b64enc }}
  DATABASE_URL: {{ printf "postgresql://%s:%s@postgres:5432/%s" .Values.postgres.credentials.username .Values.postgres.credentials.password .Values.postgres.credentials.database | b64enc }} 