version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: cdrive-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-cdrive}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - cdrive-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:postgres@postgres:5432/cdrive}
        JWT_SECRET: ${JWT_SECRET:-your_jwt_secret_here}
    container_name: cdrive-server
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:postgres@postgres:5432/cdrive}
      PORT: ${SERVER_PORT:-4000}
      JWT_SECRET: ${JWT_SECRET:-your_jwt_secret_here}
      # Add other environment variables as needed
    ports:
      - "${SERVER_PORT:-4000}:4000"
    networks:
      - cdrive-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:4000/api}
    container_name: cdrive-client
    restart: always
    depends_on:
      - server
    ports:
      - "${CLIENT_PORT:-3000}:3000"
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:4000/api}
    networks:
      - cdrive-network

networks:
  cdrive-network:
    driver: bridge

volumes:
  postgres-data: 