version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: cdrive-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cdrive
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - cdrive-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: cdrive-server
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/cdrive
      PORT: 4000
      JWT_SECRET: your_jwt_secret_here
      # Add other environment variables as needed
    ports:
      - "4000:4000"
    networks:
      - cdrive-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: cdrive-client
    restart: always
    depends_on:
      - server
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://server:4000/api
    networks:
      - cdrive-network

networks:
  cdrive-network:
    driver: bridge

volumes:
  postgres-data: 