apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cdrive
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/yourusername/cdrive.git'
    path: k8s/overlays/prod
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cdrive
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 