apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - postgres-secret.yaml
  - server-secret.yaml
  - postgres-pvc.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - server-deployment.yaml
  - server-service.yaml
  - client-deployment.yaml
  - client-service.yaml
  - ingress.yaml 