apiVersion: v1
kind: Secret
metadata:
  name: server-secret
  namespace: cdrive
type: Opaque
data:
  # Base64 encoded values
  JWT_SECRET: eW91cl9qd3Rfc2VjcmV0X2hlcmU=  # "your_jwt_secret_here"
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQHBvc3RncmVzOjU0MzIvY2RyaXZl  # "postgresql://postgres:postgres@postgres:5432/cdrive" 