apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-

resources:
  - ../../base

replicas:
  - name: server
    count: 1
  - name: client
    count: 1

images:
  - name: ${SERVER_IMAGE}
    newName: gcr.io/cdrive-dev/server
    newTag: latest
  - name: ${CLIENT_IMAGE}
    newName: gcr.io/cdrive-dev/client
    newTag: latest

patchesStrategicMerge:
  - ingress-patch.yaml 